import { spawn, type ChildProcess } from "node:child_process";
import { accessSync, constants } from "node:fs";
import { createRequire } from "node:module";

import { z } from "zod";

import { ApiError } from "../errors.js";

/*
 * The only place Retr0Vault runs ffmpeg/ffprobe. Arguments are always built
 * from fixed lists in this module and its callers; file paths are generated by
 * MotionStorage and numbers are validated before they are formatted, so no
 * user-supplied text ever reaches a command line. Processes run without a
 * shell, with a timeout and bounded output, and are killed on shutdown.
 */

const require = createRequire(import.meta.url);

export interface MotionTools {
  readonly ffmpeg: string;
  readonly ffprobe: string;
}

function executable(path: string | undefined): string | undefined {
  if (path === undefined) return undefined;
  try {
    accessSync(path, constants.X_OK);
    return path;
  } catch {
    return undefined;
  }
}

function bundledFfmpeg(): string | undefined {
  try {
    const path = require("ffmpeg-static") as unknown;
    return typeof path === "string" ? path : undefined;
  } catch {
    return undefined;
  }
}

function bundledFfprobe(): string | undefined {
  try {
    const installer = require("@ffprobe-installer/ffprobe") as { path?: unknown };
    return typeof installer.path === "string" ? installer.path : undefined;
  } catch {
    return undefined;
  }
}

/** Explicit overrides win; otherwise the npm-bundled binaries. Undefined when neither runs. */
export function resolveMotionTools(overrides: { ffmpegPath?: string | undefined; ffprobePath?: string | undefined } = {}):
  MotionTools | undefined {
  const ffmpeg = executable(overrides.ffmpegPath ?? bundledFfmpeg());
  const ffprobe = executable(overrides.ffprobePath ?? bundledFfprobe());
  return ffmpeg === undefined || ffprobe === undefined ? undefined : { ffmpeg, ffprobe };
}

export function motionToolsUnavailable(): ApiError {
  return new ApiError(503, "MOTION_TOOLS_UNAVAILABLE",
    "ffmpeg/ffprobe are unavailable. Run `npm approve-scripts ffmpeg-static` then `npm rebuild ffmpeg-static`, or set FFMPEG_PATH and FFPROBE_PATH");
}

export class ToolError extends Error {
  public constructor(message: string, public readonly kind: "timeout" | "exit" | "output" | "aborted" | "spawn") {
    super(message);
    this.name = "ToolError";
  }
}

export interface RunOptions {
  readonly timeoutMs: number;
  /** Maximum bytes kept from stdout when no consumer is supplied. */
  readonly maxStdoutBytes?: number;
  /** Streaming consumer; when present stdout is not buffered. */
  readonly onStdout?: (chunk: Buffer) => void;
  readonly signal?: AbortSignal | undefined;
}

const maximumStderrBytes = 64 * 1_024;
const running = new Set<ChildProcess>();

/** Kills every running tool process; used on API shutdown. */
export function killRunningTools(): void {
  for (const child of running) child.kill("SIGKILL");
}

export function runTool(binary: string, args: readonly string[], options: RunOptions): Promise<Buffer> {
  return new Promise((resolvePromise, reject) => {
    if (options.signal?.aborted) {
      reject(new ToolError("Processing was cancelled", "aborted"));
      return;
    }
    let child: ChildProcess;
    try {
      child = spawn(binary, args, { shell: false, windowsHide: true, stdio: ["ignore", "pipe", "pipe"] });
    } catch {
      reject(new ToolError("Media tool could not be started", "spawn"));
      return;
    }
    running.add(child);
    const stdout: Buffer[] = [];
    let stdoutBytes = 0;
    let stderr = "";
    let failure: ToolError | undefined;
    const fail = (error: ToolError) => {
      if (failure === undefined) failure = error;
      child.kill("SIGKILL");
    };
    const timer = setTimeout(() => fail(new ToolError("Media processing timed out", "timeout")), options.timeoutMs);
    const onAbort = () => fail(new ToolError("Processing was cancelled", "aborted"));
    options.signal?.addEventListener("abort", onAbort, { once: true });

    child.stdout!.on("data", (chunk: Buffer) => {
      if (options.onStdout !== undefined) {
        try {
          options.onStdout(chunk);
        } catch (error) {
          fail(new ToolError(error instanceof Error ? error.message : "Output could not be processed", "output"));
        }
        return;
      }
      stdoutBytes += chunk.length;
      if (stdoutBytes > (options.maxStdoutBytes ?? 16 * 1_024 * 1_024)) {
        fail(new ToolError("Media tool output exceeded its limit", "output"));
        return;
      }
      stdout.push(chunk);
    });
    child.stderr!.on("data", (chunk: Buffer) => {
      if (stderr.length < maximumStderrBytes) stderr += chunk.toString("utf8").slice(0, maximumStderrBytes - stderr.length);
    });
    child.on("error", () => fail(new ToolError("Media tool could not be started", "spawn")));
    child.on("close", (code) => {
      clearTimeout(timer);
      running.delete(child);
      options.signal?.removeEventListener("abort", onAbort);
      if (failure !== undefined) {
        reject(failure);
      } else if (code !== 0) {
        // Keep only the last stderr line; it is the useful part and never includes our paths twice.
        const lastLine = stderr.trim().split(/\r?\n/u).at(-1) ?? "";
        reject(new ToolError(`Media tool failed${lastLine ? `: ${lastLine.slice(0, 300)}` : ""}`, "exit"));
      } else {
        resolvePromise(Buffer.concat(stdout));
      }
    });
  });
}

// ---------------------------------------------------------------------------
// ffprobe
// ---------------------------------------------------------------------------

const probeSchema = z.object({
  streams: z.array(z.object({
    codec_type: z.string().optional(),
    codec_name: z.string().optional(),
    pix_fmt: z.string().optional(),
    width: z.number().int().optional(),
    height: z.number().int().optional(),
    avg_frame_rate: z.string().optional(),
    r_frame_rate: z.string().optional(),
    duration: z.string().optional(),
    disposition: z.object({ attached_pic: z.number().optional() }).partial().optional(),
    tags: z.object({ rotate: z.string().optional() }).partial().optional(),
    side_data_list: z.array(z.object({ rotation: z.number().optional() }).partial()).optional(),
  }).passthrough()).default([]),
  format: z.object({
    format_name: z.string().optional(),
    duration: z.string().optional(),
    size: z.string().optional(),
  }).passthrough().optional(),
}).passthrough();

export interface ProbeResult {
  readonly formatName: string;
  readonly codec: string;
  readonly pixelFormat: string | undefined;
  readonly width: number;
  readonly height: number;
  readonly fps: number;
  readonly durationMs: number;
  readonly videoStreamCount: number;
}

function parseRate(value: string | undefined): number | undefined {
  if (value === undefined) return undefined;
  const [numerator, denominator] = value.split("/").map(Number);
  if (numerator === undefined || !Number.isFinite(numerator) || numerator <= 0) return undefined;
  const rate = denominator === undefined ? numerator : denominator > 0 ? numerator / denominator : undefined;
  return rate !== undefined && Number.isFinite(rate) && rate > 0 && rate <= 1_000 ? rate : undefined;
}

export class UnsupportedMediaError extends Error {}

export async function probeMedia(tools: MotionTools, path: string, timeoutMs = 30_000): Promise<ProbeResult> {
  let output: Buffer;
  try {
    output = await runTool(tools.ffprobe, [
      "-v", "error", "-print_format", "json", "-show_format", "-show_streams", "--", path,
    ], { timeoutMs, maxStdoutBytes: 2 * 1_024 * 1_024 });
  } catch (error) {
    if (error instanceof ToolError && error.kind === "exit") throw new UnsupportedMediaError("The file is not a readable video");
    throw error;
  }
  let parsed: z.infer<typeof probeSchema>;
  try {
    parsed = probeSchema.parse(JSON.parse(output.toString("utf8")));
  } catch {
    throw new UnsupportedMediaError("The file is not a readable video");
  }
  const videoStreams = parsed.streams.filter((stream) => stream.codec_type === "video" && stream.disposition?.attached_pic !== 1);
  const video = videoStreams[0];
  if (video === undefined || video.width === undefined || video.height === undefined || video.codec_name === undefined) {
    throw new UnsupportedMediaError("The file does not contain a video stream");
  }
  const rotation = Math.abs(Number(video.tags?.rotate ?? video.side_data_list?.find((entry) => entry.rotation !== undefined)?.rotation ?? 0)) % 180;
  const width = rotation === 90 ? video.height : video.width;
  const height = rotation === 90 ? video.width : video.height;
  const durationSeconds = Number(video.duration ?? parsed.format?.duration);
  const fps = parseRate(video.avg_frame_rate) ?? parseRate(video.r_frame_rate);
  if (!Number.isFinite(durationSeconds) || durationSeconds <= 0 || fps === undefined || width <= 0 || height <= 0) {
    throw new UnsupportedMediaError("The video duration, frame rate or dimensions could not be read");
  }
  return {
    formatName: parsed.format?.format_name ?? "unknown",
    codec: video.codec_name,
    pixelFormat: video.pix_fmt,
    width,
    height,
    fps: Math.round(fps * 1_000) / 1_000,
    durationMs: Math.round(durationSeconds * 1_000),
    videoStreamCount: videoStreams.length,
  };
}

/** Formats a validated millisecond offset as an ffmpeg time argument. */
export function seconds(ms: number): string {
  if (!Number.isFinite(ms) || ms < 0) throw new Error("Invalid time offset");
  return (Math.round(ms) / 1_000).toFixed(3);
}

/** Formats a validated positive integer for filter expressions. */
export function integerArgument(value: number): string {
  if (!Number.isInteger(value) || value <= 0 || value > 100_000) throw new Error("Invalid numeric argument");
  return String(value);
}
